/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dao;

import Pracownicy.APracownik;
import Pracownicy.TYP_PRACOWNIKA;
import dao.mappers.IMapResultSetIntoEntity;
import dao.uow.IUnitOfWork;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author TKK
 */
public class PracownikRepository extends RepositoryBase<APracownik> {

    private final String TABLE_NAME = "pracownicy";

    public PracownikRepository(Connection connection, IMapResultSetIntoEntity<APracownik> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);
    }

    @Override
    protected String insertSql() {
        return "Insert into "
                + tableName()
                + " (imie, nazwisko, pensja, id_typ_pracownika)"
                + " values (?,?,?,?)";
    }

    @Override
    protected String updateSql() {
        return "update "
                + tableName()
                + " set (imie, nazwisko, pensja, id_typ_pracownika) ="
                + "(?,?,?,?) "
                + "where "
                + "id = ?";
    }

    @Override
    protected void setUpdate(APracownik entity) throws SQLException {
        update.setString(1, entity.getImie());
        update.setString(2, entity.getNazwisko());
        update.setDouble(3, entity.getPensja());
        update.setInt(4, entity.getTypPracownika().getId());
    }

    @Override
    protected void setInsert(APracownik entity) throws SQLException {
        insert.setString(1, entity.getImie());
        insert.setString(2, entity.getNazwisko());
        insert.setDouble(3, entity.getPensja());
        insert.setInt(4, entity.getTypPracownika().getId());
    }

    @Override
    protected String createTableSql() {
        return "create table "
                + tableName()
                + " (int id generated by default as identity primary key,"
                + " imie varchar(20),"
                + " nazwisko varchar(20),"
                + " pensja double,"
                + " id_typ_pracownika int,"
                + "foreign key (id_typ_pracownika) references typ_pracownika(id))";
    }

    @Override
    protected String tableName() {
        return TABLE_NAME;
    }

}
