/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dao;

import Pracownicy.APracownik;
import Pracownicy.TYP_PRACOWNIKA;
import dao.mappers.IMapResultSetIntoEntity;
import dao.model.IHaveId;
import dao.uow.IUnitOfWork;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author TKK
 */
public class Typ_Pracownika extends RepositoryBase<TYP_PRACOWNIKA>{
    
    private final String TABLE_NAME = "typ_pracownika";
    
    @Override
    protected String createTableSql() {
        return "create table "
                + tableName()
                + " (int id generated by default as identity primary key,"
                + " imie varchar(20),"
                + " nazwisko varchar(20),"
                + " pensja double,"
                + " id_typ_pracownika int,"
                + "foreign key (id_typ_pracownika) references typ_pracownika(id))";
    }

    @Override
    protected String insertSql() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    protected String updateSql() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    protected void setUpdate(TYP_PRACOWNIKA entity) throws SQLException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    protected void setInsert(TYP_PRACOWNIKA entity) throws SQLException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    protected String tableName() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
